### PR TITLE
Add latest version

### PR DESCRIPTION
**Pull request by kevinheavey**
Motivation: I want the latest version of construct in a conda package. Core requirements haven't changed.

@conda-forge-admin, please rerender

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@kevinheavey I would suggest that you add yourself as maintainer such that you can commit the new version in the future

**Comment by kevinheavey** [comment]
> @kevinheavey I would suggest that you add yourself as maintainer such that you can commit the new version in the future

Done

**Comment by tdegeus** [comment]
Awesome. You can ping the core team on gitter to ask them merge this

**Comment by kevinheavey** [comment]
@conda-forge-admin, please rerender

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
